"""
Analyze commit types from raw commit data.
Uses data from raw_commits_data.json (generated by collect_commits.py).
Classifies commits into categories: feat, fix, refactor, ci, chore, other.
"""
import json
import csv
import re
from collections import Counter
from pathlib import Path

PATTERNS = {
    "feat": re.compile(r"\b(feat|feature|add|implement|new)\b", re.I),
    "fix": re.compile(r"\b(fix|bug|error|issue|patch|hotfix)\b", re.I),
    "refactor": re.compile(r"\b(refactor|cleanup|rework|rewrite|simplify)\b", re.I),
    "ci": re.compile(r"\b(ci|pipeline|workflow|docker|build)\b", re.I),
    "chore": re.compile(r"\b(chore|deps|dependency|bump|version|format|lint)\b", re.I),
}

def classify_commit(msg):
    for cat, pattern in PATTERNS.items():
        if pattern.search(msg):
            return cat
    return "other"

def main():
    data_file = Path("3-activite-contributeurs/data/raw_commits_data.json")
    if not data_file.exists():
        print("Executez d'abord: python collect_commits.py")
        return
    
    with open(data_file, 'r', encoding='utf-8') as f:
        repos_data = json.load(f)
    
    print(f"Analyse de {len(repos_data)} repos")
    
    results = []
    
    for repo_name, repo_data in repos_data.items():
        commits = repo_data.get('commits', [])
        
        if not commits:
            print(f"[WARN] {repo_name}: Aucun commit")
            continue
        
        print(f"Analyse {repo_name}: {len(commits)} commits")
        
        counts = Counter(classify_commit(m) for m in commits)
        
        results.append({
            "repo": repo_name,
            "feat": counts.get("feat", 0),
            "fix": counts.get("fix", 0),
            "refactor": counts.get("refactor", 0),
            "ci": counts.get("ci", 0),
            "chore": counts.get("chore", 0),
            "other": counts.get("other", 0),
            "total_commits": len(commits)
        })
    
    if results:
        output_file = Path("3-activite-contributeurs/data/commits_types.csv")
        fieldnames = ["repo", "feat", "fix", "refactor", "ci", "chore", "other", "total_commits"]
        
        with open(output_file, 'w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(results)
        
        print(f"[OK] Resultats dans {output_file} ({len(results)} repos)")
    else:
        print("[ERREUR] Aucun resultat")

if __name__ == "__main__":
    main()
